nohup: ignoring input
/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/torch/cuda/__init__.py:63: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]
/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/transformers/utils/hub.py:111: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
INFO 10-01 22:24:52 [__init__.py:216] Automatically detected platform cuda.
[1;36m(APIServer pid=1178562)[0;0m INFO 10-01 22:24:54 [api_server.py:1896] vLLM API server version 0.10.2
[1;36m(APIServer pid=1178562)[0;0m INFO 10-01 22:24:54 [utils.py:328] non-default args: {'model_tag': '/home/stewa/ai-models/weights/TheBloke/llava-v1.5-13B-AWQ', 'host': '0.0.0.0', 'port': 24002, 'chat_template': 'llava15_vicuna.jinja', 'model': '/home/stewa/ai-models/weights/TheBloke/llava-v1.5-13B-AWQ', 'trust_remote_code': True, 'max_model_len': 3072, 'enforce_eager': True, 'served_model_name': ['llava-1.5-13b-awq']}
[1;36m(APIServer pid=1178562)[0;0m The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
[1;36m(APIServer pid=1178562)[0;0m INFO 10-01 22:24:58 [__init__.py:742] Resolved architecture: LlamaForCausalLM
[1;36m(APIServer pid=1178562)[0;0m `torch_dtype` is deprecated! Use `dtype` instead!
[1;36m(APIServer pid=1178562)[0;0m INFO 10-01 22:24:58 [__init__.py:1815] Using max model len 3072
[1;36m(APIServer pid=1178562)[0;0m WARNING 10-01 22:24:58 [_ipex_ops.py:16] Import error msg: No module named 'intel_extension_for_pytorch'
[1;36m(APIServer pid=1178562)[0;0m INFO 10-01 22:24:58 [awq_marlin.py:117] The model is convertible to awq_marlin during runtime. Using awq_marlin kernel.
[1;36m(APIServer pid=1178562)[0;0m INFO 10-01 22:24:58 [scheduler.py:222] Chunked prefill is enabled with max_num_batched_tokens=2048.
[1;36m(APIServer pid=1178562)[0;0m INFO 10-01 22:24:58 [__init__.py:3400] Cudagraph is disabled under eager mode
/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/torch/cuda/__init__.py:63: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]
/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/transformers/utils/hub.py:111: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
INFO 10-01 22:25:00 [__init__.py:216] Automatically detected platform cuda.
[1;36m(EngineCore_DP0 pid=1178708)[0;0m INFO 10-01 22:25:02 [core.py:654] Waiting for init message from front-end.
[1;36m(EngineCore_DP0 pid=1178708)[0;0m INFO 10-01 22:25:02 [core.py:76] Initializing a V1 LLM engine (v0.10.2) with config: model='/home/stewa/ai-models/weights/TheBloke/llava-v1.5-13B-AWQ', speculative_config=None, tokenizer='/home/stewa/ai-models/weights/TheBloke/llava-v1.5-13B-AWQ', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=3072, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=awq_marlin, enforce_eager=True, kv_cache_dtype=auto, device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=llava-1.5-13b-awq, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":0,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":null,"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":0,"use_cudagraph":true,"cudagraph_num_of_warmups":0,"cudagraph_capture_sizes":[],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"pass_config":{},"max_capture_size":0,"local_cache_dir":null}
[1;36m(EngineCore_DP0 pid=1178708)[0;0m WARNING 10-01 22:25:02 [interface.py:391] Using 'pin_memory=False' as WSL is detected. This may slow down the performance.
[1;36m(EngineCore_DP0 pid=1178708)[0;0m ERROR 10-01 22:25:02 [core.py:718] EngineCore failed to start.
[1;36m(EngineCore_DP0 pid=1178708)[0;0m ERROR 10-01 22:25:02 [core.py:718] Traceback (most recent call last):
[1;36m(EngineCore_DP0 pid=1178708)[0;0m ERROR 10-01 22:25:02 [core.py:718]   File "/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 709, in run_engine_core
[1;36m(EngineCore_DP0 pid=1178708)[0;0m ERROR 10-01 22:25:02 [core.py:718]     engine_core = EngineCoreProc(*args, **kwargs)
[1;36m(EngineCore_DP0 pid=1178708)[0;0m ERROR 10-01 22:25:02 [core.py:718]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP0 pid=1178708)[0;0m ERROR 10-01 22:25:02 [core.py:718]   File "/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 505, in __init__
[1;36m(EngineCore_DP0 pid=1178708)[0;0m ERROR 10-01 22:25:02 [core.py:718]     super().__init__(vllm_config, executor_class, log_stats,
[1;36m(EngineCore_DP0 pid=1178708)[0;0m ERROR 10-01 22:25:02 [core.py:718]   File "/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 82, in __init__
[1;36m(EngineCore_DP0 pid=1178708)[0;0m ERROR 10-01 22:25:02 [core.py:718]     self.model_executor = executor_class(vllm_config)
[1;36m(EngineCore_DP0 pid=1178708)[0;0m ERROR 10-01 22:25:02 [core.py:718]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP0 pid=1178708)[0;0m ERROR 10-01 22:25:02 [core.py:718]   File "/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 54, in __init__
[1;36m(EngineCore_DP0 pid=1178708)[0;0m ERROR 10-01 22:25:02 [core.py:718]     self._init_executor()
[1;36m(EngineCore_DP0 pid=1178708)[0;0m ERROR 10-01 22:25:02 [core.py:718]   File "/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 48, in _init_executor
[1;36m(EngineCore_DP0 pid=1178708)[0;0m ERROR 10-01 22:25:02 [core.py:718]     self.collective_rpc("init_device")
[1;36m(EngineCore_DP0 pid=1178708)[0;0m ERROR 10-01 22:25:02 [core.py:718]   File "/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 58, in collective_rpc
[1;36m(EngineCore_DP0 pid=1178708)[0;0m ERROR 10-01 22:25:02 [core.py:718]     answer = run_method(self.driver_worker, method, args, kwargs)
[1;36m(EngineCore_DP0 pid=1178708)[0;0m ERROR 10-01 22:25:02 [core.py:718]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP0 pid=1178708)[0;0m ERROR 10-01 22:25:02 [core.py:718]   File "/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/vllm/utils/__init__.py", line 3060, in run_method
[1;36m(EngineCore_DP0 pid=1178708)[0;0m ERROR 10-01 22:25:02 [core.py:718]     return func(*args, **kwargs)
[1;36m(EngineCore_DP0 pid=1178708)[0;0m ERROR 10-01 22:25:02 [core.py:718]            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP0 pid=1178708)[0;0m ERROR 10-01 22:25:02 [core.py:718]   File "/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/vllm/worker/worker_base.py", line 611, in init_device
[1;36m(EngineCore_DP0 pid=1178708)[0;0m ERROR 10-01 22:25:02 [core.py:718]     self.worker.init_device()  # type: ignore
[1;36m(EngineCore_DP0 pid=1178708)[0;0m ERROR 10-01 22:25:02 [core.py:718]     ^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP0 pid=1178708)[0;0m ERROR 10-01 22:25:02 [core.py:718]   File "/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 180, in init_device
[1;36m(EngineCore_DP0 pid=1178708)[0;0m ERROR 10-01 22:25:02 [core.py:718]     raise ValueError(
[1;36m(EngineCore_DP0 pid=1178708)[0;0m ERROR 10-01 22:25:02 [core.py:718] ValueError: Free memory on device (13.45/15.99 GiB) on startup is less than desired GPU memory utilization (0.9, 14.39 GiB). Decrease GPU memory utilization or reduce GPU memory used by other processes.
[1;36m(EngineCore_DP0 pid=1178708)[0;0m Process EngineCore_DP0:
[1;36m(EngineCore_DP0 pid=1178708)[0;0m Traceback (most recent call last):
[1;36m(EngineCore_DP0 pid=1178708)[0;0m   File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
[1;36m(EngineCore_DP0 pid=1178708)[0;0m     self.run()
[1;36m(EngineCore_DP0 pid=1178708)[0;0m   File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
[1;36m(EngineCore_DP0 pid=1178708)[0;0m     self._target(*self._args, **self._kwargs)
[1;36m(EngineCore_DP0 pid=1178708)[0;0m   File "/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 722, in run_engine_core
[1;36m(EngineCore_DP0 pid=1178708)[0;0m     raise e
[1;36m(EngineCore_DP0 pid=1178708)[0;0m   File "/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 709, in run_engine_core
[1;36m(EngineCore_DP0 pid=1178708)[0;0m     engine_core = EngineCoreProc(*args, **kwargs)
[1;36m(EngineCore_DP0 pid=1178708)[0;0m                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP0 pid=1178708)[0;0m   File "/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 505, in __init__
[1;36m(EngineCore_DP0 pid=1178708)[0;0m     super().__init__(vllm_config, executor_class, log_stats,
[1;36m(EngineCore_DP0 pid=1178708)[0;0m   File "/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 82, in __init__
[1;36m(EngineCore_DP0 pid=1178708)[0;0m     self.model_executor = executor_class(vllm_config)
[1;36m(EngineCore_DP0 pid=1178708)[0;0m                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP0 pid=1178708)[0;0m   File "/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 54, in __init__
[1;36m(EngineCore_DP0 pid=1178708)[0;0m     self._init_executor()
[1;36m(EngineCore_DP0 pid=1178708)[0;0m   File "/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 48, in _init_executor
[1;36m(EngineCore_DP0 pid=1178708)[0;0m     self.collective_rpc("init_device")
[1;36m(EngineCore_DP0 pid=1178708)[0;0m   File "/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 58, in collective_rpc
[1;36m(EngineCore_DP0 pid=1178708)[0;0m     answer = run_method(self.driver_worker, method, args, kwargs)
[1;36m(EngineCore_DP0 pid=1178708)[0;0m              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP0 pid=1178708)[0;0m   File "/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/vllm/utils/__init__.py", line 3060, in run_method
[1;36m(EngineCore_DP0 pid=1178708)[0;0m     return func(*args, **kwargs)
[1;36m(EngineCore_DP0 pid=1178708)[0;0m            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP0 pid=1178708)[0;0m   File "/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/vllm/worker/worker_base.py", line 611, in init_device
[1;36m(EngineCore_DP0 pid=1178708)[0;0m     self.worker.init_device()  # type: ignore
[1;36m(EngineCore_DP0 pid=1178708)[0;0m     ^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP0 pid=1178708)[0;0m   File "/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 180, in init_device
[1;36m(EngineCore_DP0 pid=1178708)[0;0m     raise ValueError(
[1;36m(EngineCore_DP0 pid=1178708)[0;0m ValueError: Free memory on device (13.45/15.99 GiB) on startup is less than desired GPU memory utilization (0.9, 14.39 GiB). Decrease GPU memory utilization or reduce GPU memory used by other processes.
[1;36m(EngineCore_DP0 pid=1178708)[0;0m Exception ignored in: <function ExecutorBase.__del__ at 0x757b7741d9e0>
[1;36m(EngineCore_DP0 pid=1178708)[0;0m Traceback (most recent call last):
[1;36m(EngineCore_DP0 pid=1178708)[0;0m   File "/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 237, in __del__
[1;36m(EngineCore_DP0 pid=1178708)[0;0m     self.shutdown()
[1;36m(EngineCore_DP0 pid=1178708)[0;0m   File "/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 76, in shutdown
[1;36m(EngineCore_DP0 pid=1178708)[0;0m     worker.shutdown()
[1;36m(EngineCore_DP0 pid=1178708)[0;0m   File "/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/vllm/worker/worker_base.py", line 528, in shutdown
[1;36m(EngineCore_DP0 pid=1178708)[0;0m     self.worker.shutdown()
[1;36m(EngineCore_DP0 pid=1178708)[0;0m   File "/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 675, in shutdown
[1;36m(EngineCore_DP0 pid=1178708)[0;0m     self.model_runner.ensure_kv_transfer_shutdown()
[1;36m(EngineCore_DP0 pid=1178708)[0;0m     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP0 pid=1178708)[0;0m AttributeError: 'NoneType' object has no attribute 'ensure_kv_transfer_shutdown'
[1;36m(APIServer pid=1178562)[0;0m Traceback (most recent call last):
[1;36m(APIServer pid=1178562)[0;0m   File "/home/stewa/code/imageworks/.venv/bin/vllm", line 10, in <module>
[1;36m(APIServer pid=1178562)[0;0m     sys.exit(main())
[1;36m(APIServer pid=1178562)[0;0m              ^^^^^^
[1;36m(APIServer pid=1178562)[0;0m   File "/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/vllm/entrypoints/cli/main.py", line 54, in main
[1;36m(APIServer pid=1178562)[0;0m     args.dispatch_function(args)
[1;36m(APIServer pid=1178562)[0;0m   File "/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/vllm/entrypoints/cli/serve.py", line 50, in cmd
[1;36m(APIServer pid=1178562)[0;0m     uvloop.run(run_server(args))
[1;36m(APIServer pid=1178562)[0;0m   File "/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/uvloop/__init__.py", line 109, in run
[1;36m(APIServer pid=1178562)[0;0m     return __asyncio.run(
[1;36m(APIServer pid=1178562)[0;0m            ^^^^^^^^^^^^^^
[1;36m(APIServer pid=1178562)[0;0m   File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
[1;36m(APIServer pid=1178562)[0;0m     return runner.run(main)
[1;36m(APIServer pid=1178562)[0;0m            ^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=1178562)[0;0m   File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
[1;36m(APIServer pid=1178562)[0;0m     return self._loop.run_until_complete(task)
[1;36m(APIServer pid=1178562)[0;0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=1178562)[0;0m   File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
[1;36m(APIServer pid=1178562)[0;0m   File "/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/uvloop/__init__.py", line 61, in wrapper
[1;36m(APIServer pid=1178562)[0;0m     return await main
[1;36m(APIServer pid=1178562)[0;0m            ^^^^^^^^^^
[1;36m(APIServer pid=1178562)[0;0m   File "/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 1941, in run_server
[1;36m(APIServer pid=1178562)[0;0m     await run_server_worker(listen_address, sock, args, **uvicorn_kwargs)
[1;36m(APIServer pid=1178562)[0;0m   File "/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 1961, in run_server_worker
[1;36m(APIServer pid=1178562)[0;0m     async with build_async_engine_client(
[1;36m(APIServer pid=1178562)[0;0m   File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
[1;36m(APIServer pid=1178562)[0;0m     return await anext(self.gen)
[1;36m(APIServer pid=1178562)[0;0m            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=1178562)[0;0m   File "/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 179, in build_async_engine_client
[1;36m(APIServer pid=1178562)[0;0m     async with build_async_engine_client_from_engine_args(
[1;36m(APIServer pid=1178562)[0;0m   File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
[1;36m(APIServer pid=1178562)[0;0m     return await anext(self.gen)
[1;36m(APIServer pid=1178562)[0;0m            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=1178562)[0;0m   File "/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 221, in build_async_engine_client_from_engine_args
[1;36m(APIServer pid=1178562)[0;0m     async_llm = AsyncLLM.from_vllm_config(
[1;36m(APIServer pid=1178562)[0;0m                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=1178562)[0;0m   File "/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/vllm/utils/__init__.py", line 1589, in inner
[1;36m(APIServer pid=1178562)[0;0m     return fn(*args, **kwargs)
[1;36m(APIServer pid=1178562)[0;0m            ^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=1178562)[0;0m   File "/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/vllm/v1/engine/async_llm.py", line 212, in from_vllm_config
[1;36m(APIServer pid=1178562)[0;0m     return cls(
[1;36m(APIServer pid=1178562)[0;0m            ^^^^
[1;36m(APIServer pid=1178562)[0;0m   File "/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/vllm/v1/engine/async_llm.py", line 136, in __init__
[1;36m(APIServer pid=1178562)[0;0m     self.engine_core = EngineCoreClient.make_async_mp_client(
[1;36m(APIServer pid=1178562)[0;0m                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=1178562)[0;0m   File "/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/vllm/v1/engine/core_client.py", line 102, in make_async_mp_client
[1;36m(APIServer pid=1178562)[0;0m     return AsyncMPClient(*client_args)
[1;36m(APIServer pid=1178562)[0;0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=1178562)[0;0m   File "/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/vllm/v1/engine/core_client.py", line 769, in __init__
[1;36m(APIServer pid=1178562)[0;0m     super().__init__(
[1;36m(APIServer pid=1178562)[0;0m   File "/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/vllm/v1/engine/core_client.py", line 448, in __init__
[1;36m(APIServer pid=1178562)[0;0m     with launch_core_engines(vllm_config, executor_class,
[1;36m(APIServer pid=1178562)[0;0m   File "/usr/lib/python3.12/contextlib.py", line 144, in __exit__
[1;36m(APIServer pid=1178562)[0;0m     next(self.gen)
[1;36m(APIServer pid=1178562)[0;0m   File "/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/vllm/v1/engine/utils.py", line 729, in launch_core_engines
[1;36m(APIServer pid=1178562)[0;0m     wait_for_engine_startup(
[1;36m(APIServer pid=1178562)[0;0m   File "/home/stewa/code/imageworks/.venv/lib/python3.12/site-packages/vllm/v1/engine/utils.py", line 782, in wait_for_engine_startup
[1;36m(APIServer pid=1178562)[0;0m     raise RuntimeError("Engine core initialization failed. "
[1;36m(APIServer pid=1178562)[0;0m RuntimeError: Engine core initialization failed. See root cause above. Failed core proc(s): {}
